[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "refracta"
name = "MangHoMagnet"
description = "Scans DCInside's PEAK gallery posts for Steam lobby links and lets you view/join them in-game."
websiteUrl = "https://github.com/refracta/PEAK-MangHoMagnet"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/com.github.manghomagnet.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/AngleSharp.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.Buffers.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.Collections.NonGeneric.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.Collections.Specialized.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.ComponentModel.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.ComponentModel.Primitives.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.ComponentModel.TypeConverter.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.IO.FileSystem.Primitives.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.Linq.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.Memory.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.Numerics.Vectors.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.Reflection.TypeExtensions.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.Runtime.CompilerServices.Unsafe.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.Text.Encoding.CodePages.dll"
target = "/"

[[build.copy]]
source = "../../artifacts/bin/MangHoMagnet/release/System.Threading.dll"
target = "/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", ]
